[versions]
adventure = "5.2.0"
gson = "2.14.0"
publish = "0.37.0"

[libraries]
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
adventure = { module = "net.kyori:adventure-api", version.ref = "adventure" }
adventure-nbt = { module = "net.kyori:adventure-nbt", version.ref = "adventure" }

[plugins]
publish = { id = "com.vanniktech.maven.publish", version.ref = "publish" }
